### ISSUE TITLE
What mapper does MISO supports?

### ISSUE THREAD

**Issue by marcowanger** [yarden/MISO#18]
I tried to run MISO to estimate insert size and compute-genes-psi

With identical parameters, annotation file provided by MISO and dataset.

Both insert size stimate and compute psi failed for BAM file generated from MapSplice and SpliceMap (both latest version). Only Tophat output's BAM run smoothly.

e.g. for SpliceMap and MapSplice's BAM, during compute-genes-psi, no files are output to output-directory. It always shows "only 0 reads in gene, skipping...."

Would like to ask which reads mapper were tested?

Thanks.

**Comment by yarden** [comment]
We tend to use Tophat but we've had other users use these other mappers successfully.

The four common reads for seeing zero reads are:

(1) missing .bai (bam index) file -- your .bai file _must_ be in the same directory as the .bam file, otherwise the BAM will appear unindexed and it will not be able to pull reads.

(2) similar to (1), if your BAM is unsorted (i.e. if samtools sort mybam was not run)

(3) if there's a headers mismatch between the GFF3 file you use with MISO and your BAM file. For example, if your BAM was generated by mapping to an Ensembl *.fa versions of the genome, which do not have "chr" prefixes to chromosome headers, but you then use a GFF3 file that does contain "chr" in the chromosome headers. Then no reads will be pulled out.

(4) You are using paired-end reads, but your BAM file does not encode which reads are properly mapped. If the BAM file has binary fields that are not set properly, MISO will think none of the read mates are properly mapped and so it will discard them. You should see this in the MISO output (it will state how many PE reads were thrown out for each gene/event.) If this is the issue, then running the same sample in single-end mode (without "--paired-end") should work.

I suggest checking (1)-(3) and verifying it's not one of these issues. If that doesn't explain it, send me a small BAM containing reads that you know should match your annotation, and a small chunk of the GFF3 file you ran it with, and I can take a look.

Best, --Yarden

**Comment by marcowanger** [comment]
Thanks for your quick reply Yarden.

Actually my sequencing for this dataset is 75bp read length, ~200bp insert size.

I then quality trimmed down to >50bp. Since MISO does not support variable length, I discard the sequence beyond first 50bp, making all the reads appear to be 50bp

1) I have made sure to index the BAM file and place them in the same directory.

2) I have sorted them by coordinate

3) I mapped the reads onto UCSC chr, and all chr chromosomes starts with chr

So I think 1-3 is not the issues.

4) For the binary tag issues, I gave a brief check using samtools flagstat

Tophat:
3987373 in total
0 QC failure
0 duplicates
3987373 mapped (100.00%)
3987373 paired in sequencing
1996367 read1
1991006 read2
685364 properly paired (17.19%)
3844658 with itself and mate mapped
142715 singletons (3.58%)
0 with mate mapped to a different chr
0 with mate mapped to a different chr (mapQ>=5)

SpliceMap:
3666184 in total
0 QC failure
0 duplicates
3666184 mapped (100.00%)
3666184 paired in sequencing
1833513 read1
1832671 read2
0 properly paired (0.00%)
3172122 with itself and mate mapped
494062 singletons (13.48%)
0 with mate mapped to a different chr
0 with mate mapped to a different chr (mapQ>=5)

MapSplice:
4466781 in total
0 QC failure
0 duplicates
4309422 mapped (96.48%)
4309422 paired in sequencing
2158324 read1
2151098 read2
4017060 properly paired (93.22%)
4146482 with itself and mate mapped
162940 singletons (3.78%)
144327 with mate mapped to a different chr
144327 with mate mapped to a different chr (mapQ>=5)

I have sent you a email at ([yarden mit dot edu]) for the BAM.

I used the AS event annotation hg19 downloaded from MISO homepage (http://genes.mit.edu/burgelab/miso/annotations/hg19_alt_events.zip). MISO ver. (http://pypi.python.org/packages/source/m/misopy/misopy-0.4.tar.gz)

Thanks,
Marco

**Comment by marcowanger** [comment]
Running MISO in single end mode seems to work for SpliceMap and MapSplice BAM.

How is the accuracy differs from using pair-ended mode?

**Comment by yarden** [comment]
Hi Marco,

The problem looks like issue #4 -- note that for MapSplice:

# 

# 0 properly paired (0.00%)

I'm not sure about SpliceMap, will look into that BAM file later.

But since single end works for you, it does look like these BAMs do not encode the proper pairing flags. There are three general options on dealing with this:
1. Correcting the BAM files or getting your read mapper to correct them -- perhaps there's an option for that? I'd ask the MapSplice users/maintainers, since it doesn't seem right that 0% of your reads are not properly mapped (especially since other mappers can find proper mappings.)
2. Turning off MISO's filter_reads option in the settings file. This will not apply any filters when running in paired-end mode and instead will simply pair up reads by their ID. So if your file BAM file has:

my_read_id#1 ....
my_read_id#2 ....

it will treat my_read_id#1 and my_read_id#2 as paired and not check any of the binary BAM flags.

Or finally, you can run in single-end mode. Paired-end is generally better, and systematically better at some types of longer range RNA processing events, but with lots of read coverage you can still do extremely well with single end.

Best, --Yarden

**Comment by marcowanger** [comment]
Yarden,

0 properly paired is for SpliceMap.

Thanks for looking into the BAM file.

Marco

**Comment by marcowanger** [comment]
Yarden,

What puzzled me most is that.

For MapSplice, you see a majority of them are properly paired. (which means there is no #4 issue)

In the run_event_analysis --compute-genes-psi, i saw
- Executing: python /home/marco/tools/miso/misopy-0.4/misopy/run_miso.py --compute-gene-psi "chr10:95431799:95431846:-@chr10:95433495:95433566:-@chr10:95436410:95436448:-" /home/marco/tools/miso/annotation/hg19/SE/chr10/chr10:95431799:95431846:-@chr10:95433495:95433566:-@chr10:95436410:95436448:-.pickle /home/marco/tools/miso/misopy-0.4/proj.cap50.run/mapsplice1152.cap50/test.miso_estimate/s4.mapsplice1152.bam /home/marco/tools/miso/misopy-0.4/proj.cap50.run/mapsplice1152.cap50/test.miso_estimate/test.again.again --read-len 50  --paired-end 200.0 15.0 --settings-filename /usr/local/lib/python2.6/dist-packages/misopy/settings/miso_settings.txt
- Executing: python /home/marco/tools/miso/misopy-0.4/misopy/run_miso.py --compute-gene-psi "chr11:13007587:1300Loading settings from: /usr/local/lib/python2.6/dist-packages/misopy/settings/miso_settings.txt

For above, am I correct to say MISO runs on the AS events mentioned above? And result should be stored to "/home/marco/tools/miso/misopy-0.4/proj.cap50.run/mapsplice1152.cap50/test.miso_estimate/test.again.again", but there is no output there.

For the following events, I suppose there are not enough reads to support analysis.
- Executing: python /home/marco/tools/miso/misopy-0.4/misopy/run_miso.py --compute-gene-psi "chr11:13007587:1300Loading settings from: /usr/local/lib/python2.6/dist-packages/misopy/settings/miso_settings.txt
  Settings: 
  short_queue_name quick
  long_queue_name long
  cluster_command qsub
  filter_results True
  min_event_reads 20
  lag 10
  burn_in 500
  num_iters 5000
  Computing Psi for 1 genes...
  - chr11:13007587:13007691:-@chr11:13009949:13010013:-@chr11:13011003:13011095:-
  - GFF filename: /home/marco/tools/miso/annotation/hg19/SE/chr11/chr11:13007587:13007691:-@chr11:13009949:13010013:-@chr11:13011003:13011095:-.pickle
  - BAM: /home/marco/tools/miso/misopy-0.4/proj.cap50.run/mapsplice1152.cap50/test.miso_estimate/s4.mapsplice1152.bam
  - Outputting to: /home/marco/tools/miso/misopy-0.4/proj.cap50.run/mapsplice1152.cap50/test.miso_estimate/test.again.again
  - Paired-end mode:  (200.0, 15.0)
    Loading BAM filename from: /home/marco/tools/miso/misopy-0.4/proj.cap50.run/mapsplice1152.cap50/test.miso_estimate/s4.mapsplice1152.bam
    Loading took 0.02 seconds
    Filtered out 0 read pairs that were on same strand.
    Filtered out 0 reads that had no paired mate.
    Only 0 reads in gene, skipping (needed >= 20 reads)

Is it the correct interpretation on the run_event_analysis STDOUT?
