### ISSUE TITLE
Replicate on samples

### ISSUE THREAD

**Issue by marcowanger** [yarden/MISO#19]
Hi Yarden,

I have subscribed to the mail list but there is still no confirmation so I ask the question here.

MISO run_miso.py --compare-samples perform pairwise comparison. If I have replicate on the samples, what is the best strategy to combine the results?

Marco

**Comment by yarden** [comment]
We have developed some ways to deal with replicates, but they are not directly in MISO -- right now it does not handle replicates / groups in any special way.  I'd recommend processing the BAM file for each replicate separately and then also running MISO on a pooled version of the replicates (e.g. all the experimental samples and all the controls.)  We typically get a pooled estimate by just concatenating together the BAM files for each of the biological replicates into one large BAM file, and running MISO on that separately.  That way you can filter events that change by requiring them to change in the same direction (and maybe with similar orders of magnitude) in all the replicates, or most of the replicates.  If you find that the biological replicates behave similarly -- e.g. they cluster together when you cluster the Psi values obtained for each sample -- then you can then use the MISO estimates for the pooled samples only in downstream analyses.  If you have enough data/replicates, then clustering the Psi values (perhaps only the ones that are differential at least, by some Bayes factor threshold) would be a good analysis that I'd find much more convincing than a statistical test.

We find that this setup works best, since it can weed out events that show a change in only a minority of the biological replicates if you want to be conservative, but also give you power to be inclusive when needed by analyzing the pooled BAM.

You can also frame the replicates problem in traditional classical statistics terms, if you have a table of read counts supporting each isoform for an event (this is outputted by MISO -- see http://genes.mit.edu/burgelab/miso/docs/#using-the-read-class-counts for detailed description) for each replicate in your groups, and then you can see if there's a group wide difference in these counts.  This approach is less direct/convincing in my mind than what I described above, but the advantages are that it can find group differences -- in an "ANOVA-like" way -- and use established stat. techniques if you frame the problem as a table of counts.

**Comment by marcowanger** [comment]
Thanks
