### ISSUE TITLE
Detecting low or unrepresented transcripts

### ISSUE THREAD

**Issue by alig99** [yarden/MISO#33]
I have run Miso (great manual), but it is not pulling out my gene (2 Exons knocked out)

What settings do I need to include transcripts with low to no reads compared to the control?

I'm trying       filter_results = False      min_event_reads = 0      at the moment.

Thanks   alig

**Comment by yarden** [comment]
How are you running MISO? Which annotation are you using? Is it your own transcript level annotation or our alternative 'exon-centric' annotation? 

MISO outputs the genes it skips, so you can see if your gene is there. Does it pull out the gene in the non-knockout condition? It's hard to tell what is going on without more information.

**Comment by alig99** [comment]
I'm using the mm10_refGene.txt annotation retrieved from UCSC & converted to gff3.  I'm trying to run isoform-centric analyses.  It doesn't pull out the gene in the non-knockout either.

I'm running Miso as follows, (I'm new to this program)
I computed the insert length
python exon_utils.py --get-const-exons mm10_refGene.gff3 --min-exon-size 1000 --output-dir exons/
python pe_utils.py --compute-insert-len sample.bam mm10_refGene.min_1000.const_exons.gff3 --output-dir insert-dist/
python run_events_analysis.py --paired-end 224 75 --compute-genes-psi /misopy-0.4.6/indexed sample.bam --output-dir sample.output/ --read-len 100
python run_miso.py --summarize-samples sample_output/ sample_output/
python run_miso.py --compare-samples control/ knockdown/ comparisons/

I notice that my gene isn't in the index folder, but then only a fraction of the total number of genes seem to be represented in the index folder.
Thank you   alig

**Comment by yarden** [comment]
Could you show me the GFF annotation from "mm10_refGene.txt" for your gene? Does it have the proper gene -> mRNA -> exon structure?

Also, you're running MISO against the indexed version of mm10_refGene.txt and not against the output of exon_utils.py, right?

If your gene is not in the generated index, that's the root of the problem. Every gene with at least 2 isoforms gets indexed. If your gene has only one annotated isoform, that might be the reason it is skipped. Does it?

**Comment by alig99** [comment]
Okay, the mouse only has one isoform, (human has 3 isoforms).  So does that mean I cannot use Miso for my project as some of the genes pulled out by Cufflinks also only have one isoform.  

Sorry if I've wasted your time on this by not realising this requirement.

Yep, I'm running MISO against the indexed version of mm10_refGene.txt

Here are a few lines of the gff annotation from mm10_refGene.txt
chrX    refGene gene    52912266    52956943    .   +   .   ID=Phf6;Name=Phf6;Name=Phf6
chrX    refGene mRNA    52912266    52956943    .   +   .   ID=NM_027642;Parent=Phf6
chrX    refGene exon    52912266    52912436    .   +   .   ID=exon:NM_027642:1;Parent=NM_027642
chrX    refGene exon    52916553    52916736    .   +   .   ID=exon:NM_027642:2;Parent=NM_027642
chrX    refGene exon    52917166    52917267    .   +   .   ID=exon:NM_027642:3;Parent=NM_027642
chrX    refGene exon    52931573    52931706    .   +   .   ID=exon:NM_027642:4;Parent=NM_027642
chrX    refGene exon    52931981    52932024    .   +   .   ID=exon:NM_027642:5;Parent=NM_027642
chrX    refGene exon    52940225    52940391    .   +   .   ID=exon:NM_027642:6;Parent=NM_027642
chrX    refGene exon    52940537    52940680    .   +   .   ID=exon:NM_027642:7;Parent=NM_027642
chrX    refGene exon    52942564    52942668    .   +   .   ID=exon:NM_027642:8;Parent=NM_027642
chrX    refGene exon    52945884    52946017    .   +   .   ID=exon:NM_027642:9;Parent=NM_027642
chrX    refGene exon    52953452    52953578    .   +   .   ID=exon:NM_027642:10;Parent=NM_027642
chrX    refGene exon    52953906    52956943    .   +   .   ID=exon:NM_027642:11;Parent=NM_027642
chrX    refGene five_prime_UTR  52912266    52912436    .   +   .   ID=five_prime_UTR:NM_027642:1;Parent=NM_027642
chrX    refGene five_prime_UTR  52916553    52916598    .   +   .   ID=five_prime_UTR:NM_027642:2;Parent=NM_027642
chrX    refGene start_codon 52916599    52916601    .   +   0   ID=start_codon:NM_027642:1;Parent=NM_027642
chrX    refGene CDS 52916599    52916736    .   +   0   ID=CDS:NM_027642:1;Parent=NM_027642
chrX    refGene CDS 52917166    52917267    .   +   0   ID=CDS:NM_027642:2;Parent=NM_027642
chrX    refGene CDS 52931573    52931706    .   +   0   ID=CDS:NM_027642:3;Parent=NM_027642
chrX    refGene CDS 52931981    52932024    .   +   1   ID=CDS:NM_027642:4;Parent=NM_027642
chrX    refGene CDS 52940225    52940391    .   +   2   ID=CDS:NM_027642:5;Parent=NM_027642
chrX    refGene CDS 52940537    52940680    .   +   0   ID=CDS:NM_027642:6;Parent=NM_027642
chrX    refGene CDS 52942564    52942668    .   +   0   ID=CDS:NM_027642:7;Parent=NM_027642
chrX    refGene CDS 52945884    52946017    .   +   0   ID=CDS:NM_027642:8;Parent=NM_027642
chrX    refGene CDS 52953452    52953578    .   +   1   ID=CDS:NM_027642:9;Parent=NM_027642
chrX    refGene stop_codon  52953576    52953578    .   +   0   ID=stop_codon:NM_027642:1;Parent=NM_027642
chrX    refGene three_prime_UTR 52953906    52956943    .   +   .   ID=three_prime_UTR:NM_027642:1;Parent=NM_027642

**Comment by yarden** [comment]
Since MISO is meant to quantitate alternative splicing, it does not index genes that have only a single isoform. Note that MISO is not an RPKM calculator; it gives you Psi values, i.e. the percent spliced in (or in your case, percent spliced isoform) quantity. When you have only a single isoform, the Psi value is by definition 1 for that isoform. If you want to calculate RPKMs for these genes, it's much simpler (and more computationally efficient) to use something like bedtools (http://code.google.com/p/bedtools/) to retrieve the reads in those genes and calculate their RPKMs. 

It's on my list to add a flag to `index_gff.py` that optionally still indexes genes with one isoform, just for convenience (since some users want to plot these using Sashimi plot, or use the index for other purposes). However, from perspective of MISO and Psi calculations, having one isoform doesn't make much sense (there's nothing alternative to quantitate.) 

It might be worth looking into whether your refSeq annotation is actually complete for your gene of interest. refSeq tends to be conservative, and Ensembl might have an annotation that is more complete and potentially has additional isoforms. Though using refSeq is certainly a fine option too. 

In any case, you can definitely use MISO to calculate Psi values for the genes with multiple isoforms, and assume that the rest have a Psi = 1 by definition.

**Comment by alig99** [comment]
Thank you, yes I understand.  I may come back at a later date to look at alternative splicing.  But for now I'll take a look at bedtools,   alig
