### ISSUE TITLE
building with python 3 fails

### ISSUE THREAD

**Issue by rekado** [yarden/MISO#71]
`setup.py` contains this line:

```
if sys.version_info > (3, 0):
    options["use_2to3"] = True
```

but `options` has not been declared anywhere and is not used in the `setup(...)` call later on, making it impossible to build MISO under Python 3.

**Comment by yarden** [comment]
Python 3 is not backwards compatible with Python 2.7.x - it would require massive changes to the software, far beyond `setup.py`. This may happen in future but there are no immediate plans to support Python 3 because it's such a real pain to handle the backwards incompatible changes. Thank you for pointing out that line in `setup.py` though, that will be fixed.

**Comment by rekado** [comment]
That's okay.  I was just confused by that line in setup.py, because it implies that building with python 3 is supported.
